image: docker
services:
  - mongo
  - redis

stages:
  - test
  - build

test:
  stage: test
  image: maven:alpine
  script:
    - export spring_data_mongodb_host=mongo
    - export spring_redis_host=redis
    - mvn test

build:
  stage: build
  script:
    - docker run --rm -v "$PWD":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$PWD/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:alpine mvn package -DskipTests
    - DATE=`date +%Y%m%d`
    - TAG=$DATE-$CI_JOB_ID
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTER}
    - docker build -t ${DOCKER_REGISTER}/${PROJECT_NAME}:$TAG .
    - docker push ${DOCKER_REGISTER}/{PROJECT_NAME}:$TAG
    - docker tag ${DOCKER_REGISTER}/{PROJECT_NAME}:$TAG ${DOCKER_REGISTER}/{PROJECT_NAME}:latest
    - docker push ${DOCKER_REGISTER}/{PROJECT_NAME}:latest