image: docker

stages:
  # - test
  - build
  # - deploy

build:
  stage: build
  script: 
    - DATE=`date +%Y%m%d`
    - TAG=$DATE-$CI_JOB_ID
    - docker login -u admin -p SaE-WAS-8bJ-rHG kerust.net:8088
    - docker build -t kerust.net:8088/javabaas:$TAG .
    - docker push kerust.net:8088/javabaas:$TAG
